name: BaeHyeonWooPL
version: 1.2.1
main: library.Main
api-version: 1.15

commands:
  activestatus:
    description: "Plugin active status check command."
  credits:
    description: "Shows who made this plugin."
  gm:
    description: "Reference of Essentials. Changing gamemode with only gm and numbers."
  stop:
    description: "Blocking original stop command for shitz."
  whyme99:
    description: "For troll my friend. Going to be deleted."
  compass:
    description: "For convenience. WorldEdit Compass thing."
  diasetpvp:
    description: "Diamond armor PVP"
  chainsetpvp:
    description: "Chain armor PVP"
  goldsetpvp:
    description: "Gold armor PVP"
  ironsetpvp:
    description: "Iron armor PVP"
  leathersetpvp:
    description: "Leather armor PVP"
  god:
    description: "BUFFS."
  invisible:
    description: "EV"
  ev:
    description: "INVISIBLE"
  godremove:
    description: "Remove Buffs and returns to the original."
  evremove:
    description: "Removes invisibility."
  invisibilityremove:
    description: "Removes invisibility"
  classicduel:
    description: "Reference of Hypixel. Clasic Duel."
  spacemode:
    description: "HOUSTON, WE HAVE A PROBLEM."
  deactspace:
    description: "IT WAS JUST A DREAM."
  giveop:
    description: "Kicks the user just for fun. Will be opped."
  feed:
    description: "A Pizza would be nice hmm?"
  heal:
    description: "Mind damaged? I'll heal for you. But you must promise you need to heal mine too... hehe...//////"
  difficulty:
    description: "Change Difficulty in Numbers"
  gamemode:
    description: "Changing gamemode with numbers."
  stopserver:
    description: "Stops server normally."
  playwait:
    description: "Test command. Plays wait. Where are we now."
  ci:
    description: "Clears inventory."
  stopwait:
    description: "Test command."
  nightvision:
    description: "BEHOLD."
